- code/datums/keybinding/client.dm
- code/modules/client/client_defines.dm
- code/modules/client/verbs/ooc.dm
Промежуточный. Залью рабочий позже
> fullscreen

- code/modules/clothing/glasses/_glasses.dm
"A pair of glasses fitted with an analyzer for scanning items and reagents. Someone seems to have popped out the perscription lenses... "
"Очки с встроеным анализатором для сканирования вещей и реагентов. Кто-то выломал обычные линзы..."
> Перевод описания очков Science Glasses

- _maps/configs/inteq_iron_maiden.json
- _maps/shuttles/shiptest/inteq_iron_maiden.dmm
Добавления нового корабля inteq. Заодно потестим перевод профессий на картах доступа.
Новый корабль , тест моих возможностей как маппера . Надеюсь игроки оценят.
> Бот-Утюг inteq

- _maps/configs/independent_ramo.json
- _maps/shuttles/shiptest/independent_ramo.dmm
Опять же пот кровь и слезы маперов , новый кораблик нейтралов , ремо.
Новый кораблик , тест новой консольки .
> Кораблик нейтралов Рамо

- _maps/shuttles/shiptest/inteq_colossus.dmm
Починил шлюз , а также добавил в ящик с баллонами пару масок , также переделал кривое размещение адвансед аирлока.
Ремонт кораблика , небольшое косметическое изменение.
> Небольшой ремонт шлюза Colossus

- _maps/shuttles/shiptest/nanotrasen_ranger.dmm
Апдейт рейнджера по просьбам трудящихся
1. Добавил джетов в хранилищах ригов
2. Коммандера в шкафчике комиссара
3. Две флешеки для создания борга в ящике около смеса
4. Брут аптечку в мед 
5. Речарджер для егана лейтенанта, на мостик капитана
> Небольшой апдейт корабля класса Рейнджер

- _maps/shuttles/shiptest/syndicate_twinkleshine.dmm
Автор Hayden Hardy | Where Officer?
> Фикс Твинклшайна

- _maps/outpost/outpost_test_1.dmm
- _maps/outpost/outpost_test_2.dmm
Автор Hayden Hardy | Where Officer?
> Обновление оутпостов

- _maps/configs/syndicate_kaas.json
- _maps/shuttles/shiptest/syndicate_kaas.dmm
Автор корабля Hayden Hardy | Where Officer?. Насколько понимаю корабль нужно не в свободный доступ а в щитспавн.
> Новый корабль ЕРТ синдиката

- _maps/shuttles/shiptest/syndicate_cybersun_remora.dmm
- _maps/shuttles/shiptest/syndicate_kaas.dmm
Апдейт кораблей
Ремора.
Каас
Ремора
1.Ребаланс снаряжения
2.Перестройка РнД , мостика , вирусологии.
Каас
1.Исправление зон
> Апдейт Ремора , Каас

- _maps/shuttles/shiptest/independent_lagoon.dmm
Работа по заявке. .Моника Кейли Катя Самбука
Добавлены отсутствующие АПЦ , выключатели света , Эир алярмы.
Добавлены кнопки для болтирования дверей в жилых комнатах.
Исправлены задвижки окон в инженерном отсеке
Исправлен шкафчик в инженерном отсеке.
Исправлен шлюз в носовой части корабля
В карго автоматы wt550 заменены на smg CR-5
Небольшой косметический ремонт в жилых комнатах.
> Апдейт корабля Лагуна

- code/game/MapData/shuttles/nanotrasen_ranger.dm
> LP Hardsuit Buff

- _maps/configs/independent_ramo.json
- _maps/shuttles/shiptest/independent_ramo.dmm
Заменил оутфит инженера. Тем самым починив рантайм эррор.
> Апдейт конфига рамо , исправление багулины.

- _maps/configs/syndicate_cybersun_remora.json
- _maps/shuttles/shiptest/syndicate_cybersun_remora.dmm
- code/modules/jobs/job_types/chemist.dm
- code/modules/jobs/job_types/station_engineer.dm
1.Нерф бимганов
2.Косметические улучшения
3.Починка профессий и критической ошибки связанной с ней. 4.Удаление лишней ПП в ящике парамеда.
> Ремонт Реморы

- _maps/shuttles/shiptest/minutemen_vela.dmm
1.Добавление модуля борис к платам ИИ
> Апдейт Вела класс

- _maps/shuttles/shiptest/nanotrasen_delta.dmm
1.Добавление платы борис к модулям ИИ
> Апдейт дельта - класс

- _maps/shuttles/shiptest/nanotrasen_ranger.dmm
1.Исправлен комплект - собери борга сам. Теперь деействительно можно собрать борга. 
2.Добавлен мед худ в шкафчик врача.
> Небольшой ремонт рейнджера по заявкам.

- _maps/shuttles/shiptest/syndicate_cybersun_remora.dmm
> Ремора финал

- _maps/shuttles/shiptest/syndicate_cybersun_remora.dmm
- code/game/objects/items/robot/robot_upgrades.dm
1.Исправлен модуль выбора синди борга
2.Заменена плата выбора синди борга на верную.
> Обновление Реморы

- _maps/shuttles/shiptest/pirate_santiana.dmm
Небольшой ремонт предыдущих багов.
Добавления платы рипли , шасси рипли , исправление интерьера и проводки.
> Обновление сантианы

- _maps/configs/syndicate_kaas.json
- _maps/shuttles/shiptest/syndicate_kaas.dmm
- code/modules/jobs/job_types/brig_physician.dm
- code/modules/jobs/job_types/captain.dm
- code/modules/jobs/job_types/head_of_security.dm
- code/modules/jobs/job_types/security_officer.dm
- code/modules/jobs/job_types/station_engineer.dm
> разрешённые конфликты экстазера?

- _maps/configs/syndicate_kaas.json
- _maps/shuttles/shiptest/syndicate_kaas.dmm
- code/modules/jobs/job_types/brig_physician.dm
- code/modules/jobs/job_types/captain.dm
- code/modules/jobs/job_types/head_of_security.dm
- code/modules/jobs/job_types/security_officer.dm
- code/modules/jobs/job_types/station_engineer.dm
Добавлены новые роли для корабля.
Captain - Commander
Head of Security - Lieutenant Commander
Security Officer - Lieutenant
Medic - Lieutenant Junior Grade Medic
Engineer - Lieutenant Junior Grade Engineer
Добавлены новые вещи в шкаф лейтенанта:
2 сумки x4 ( бомб )
3 маяка синди бомб
Коробки патронов и магазины для APS 9мм
ЕМАГ ограниченного использования ( 15 использований )
> Роли и маленькие правки

- _maps/configs/independent_qurk.json
- _maps/shuttles/shiptest/independent_qurk.dmm
Добавление независимого мед корабля , корабль щитспавн , уровня реморы но без синдикатовского стаффа.
> Добавление щитспавн корабля Курк

- _maps/configs/nanotrasen_venture.json
- _maps/shuttles/shiptest/nanotrasen_venture.dmm
Добавление шахтерского шаттла поддержки , Нанотрейзен. Расчитан на экипаж из 1-2 человек. Основная задача добыча ресурсов для поддержки более крупных судов.
> Добавление шахтерского шаттла класса Вентура

- code/game/machinery/telecomms/broadcasting.dm
- code/game/objects/items/devices/radio/intercom.dm
- code/game/objects/items/devices/radio/radio.dm
- code/modules/mining/equipment/kinetic_crusher.dm
- tgui/packages/tgui/interfaces/Radio.js
Перенос ПРа с оффов с логами вайдбанда
https://github.com/shiptest-ss13/Shiptest/pull/2307
Заодно фикс ошибки крашеров.
> Логи вайдбанда + фикс ошибок крашера

- code/modules/research/designs/autolathe_designs.dm
Отличие от ПРа https://github.com/shiptest-ss13/Shiptest/pull/2388/files , кнопка в разделе строительство.
> Крафт выключателя света

- _maps/RandomRuins/RockRuins/rockplanet_shippingdock.dmm
- _maps/map_catalogue.txt
- code/datums/ruins/rockplanet.dm
- code/game/area/areas/ruins/rockplanet.dm
- config/rockruinblacklist.txt
Перенос ПРа https://github.com/shiptest-ss13/Shiptest/pull/2393
> Руины с оффов

- _maps/shuttles/shiptest/independent_qurk.dmm
Исправление багов https://discord.com/channels/1100198143456465067/1160622590054912040
> Обновление Курка

- _maps/configs/independent_escapepod.json
- _maps/shuttles/shiptest/independent_escapepod.dmm
Escape pod introduction
- Hardcore start with intentions to rebuild your pod and survive as long as you can
> Escape pod (solo start)

- _maps/configs/independent_escapepod.json
- _maps/configs/minutemen_proteus.json
- _maps/shuttles/shiptest/independent_escapepod.dmm
> Escapepod Update

- _maps/shuttles/shiptest/independent_escapepod.dmm
> Another fix

- code/modules/mob/living/simple_animal/guardian/types/support.dm
Guardian beacon fix?
Attemp to fix beacons sprite
> Beacon fix

- _maps/_basemap.dm
Теперь будет спавниться полный ТГшный Цент-Ком
Заработает кнопка launch supply pod, у админов появится место для военных преступлений, где их никто не потревожит
:cl:
config: Включен ЦК
/:cl:
> Включаем Цент-Ком

- code/modules/cargo/packs/machinery.dm
- code/modules/cargo/packs/vendor_refill.dm
Добавление барахла в продажу карго
Игроки перестанут ныть что за 6 часов нельзя сделать рнд
Добавлены в раздел машины и механизмы
Маяк с выбором плат для рнд с разделением на отделы
Набор плат карго телепорта и консоли к нему
Набор универсальных плат для протолата и принтера плат
Добавлены в раздел Пополнения торговых автоматов
Плата вендомата
Пополнение шахтерского вендора
Пополнение SecTech вендора
Пополнение SecDrobe вендора
> Добавление в карго разного барахла

- _maps/configs/independent_executor.json
- _maps/shuttles/shiptest/independent_executor.dmm
Кораблик наемышей с карцером, медом и оружейкой нелетала (И леталом)
> Кораблик "Исполнитель"

- _maps/configs/nanotrasen_savior.json
- _maps/shuttles/celadon/nanotrasen_savior.dmm
Новый мед шип с приколами для НТ. Слава НТ!
> Новый корабль НТ

- _maps/shuttles/shiptest/independent_executor.dmm
Починил пустой обж и пару тайлов
> hotfix-executor

- _maps/shuttles/shiptest/independent_executor.dmm
- _maps/shuttles/shiptest/nanotrasen_gecko.dmm
Добавлена бумажка на гекко с пропорциями ТЭГа. Добавлен бак с топливом и водой, а так же заменены консольки на Исполнителе.
> Хот-фикс Исполнителя и бумажка на гекко

- _maps/configs/independent_junkruiser.json
- _maps/shuttles/independent/independent_junkruiser.dmm
Новый корабль , удалена мегафауна , заменена на обычных противников , урезаны возможности РнД
> Добавление Junkкрейсера

- code/modules/cargo/exports/lavaland.dm
- code/modules/cargo/packs/machinery.dm
- code/modules/cargo/packs/vendor_refill.dm
Баунти за все трофеи с лавы уменьшены в половину , цену на спец рнд установил 9к , цену на карго пад с консолью 8к
> Очередной раз шатаем баланс

- code/datums/ai_laws.dm
- code/game/objects/items/AI_modules.dm
- code/modules/mob/living/silicon/silicon.dm
- config/silicon_laws.txt
Пофикшены кракозябры в отображении законов на кирилице
Переведен на русский набор законов крюзимов
> Фикс русиша на законы ИИ

- _maps/configs/independent_junkruiser.json
Отключаем этот кусок недоработанного корабля
> Убираем в щитспавн Джанк крейсер

- _maps/shuttles/syndicate/syndicate_cybersun_remora.dmm
https://github.com/MysticalFaceLesS/Shiptest/pull/51
Перезалив ПРа экстазера , ссылка прилагается
> Нерф реморы , ПР экстазера

- _maps/configs/syndicate_twinkleshine.json
> Вывод твинклшайн в щитспавн

- code/game/machinery/dance_machine.dm
> Починка жукбокса

- _maps/configs/syndicate_cybersun_remora.json
Ограничение на спавн реморы в 1 корабль , по просьбе Глав админа
> Ограничение на Ремору

- _maps/shuttles/InteQ/inteq_hammerhead.dmm
Небольшой апдейт хаммерхеда
Добавлено чуть больше снаряжения , переделан атмос , изменены названия дверей и машин
> Апдейт хаммерхеда

- code/modules/mob/say_vr.dm
Reverts MysticalFaceLesS/Shiptest#90
> Revert "Сабтлер"

- _maps/shuttles/independent/independent_acron.dmm
Reverts MysticalFaceLesS/Shiptest#94
> Revert "Изменение Acron-class"

- code/modules/mob/say_vr.dm
> Сабтлер версия 2.0

- _maps/shuttles/InteQ/inteq_hammerhead.dmm
Исправил неработающие жалюзи
:cl:
/:cl:
> Апдейт молотоглава

- _maps/shuttles/independent/independent_acron.dmm
- code/__DEFINES/traits.dm
- code/acron/spaceninja.dm
- code/datums/dash_weapon.dm
- code/game/objects/items/defib.dm
- code/game/objects/items/storage/backpack.dm
- code/modules/ninja/energy_katana.dm
- code/modules/ninja/suit/n_suit_verbs/ninja_cost_check.dm
- code/modules/ninja/suit/n_suit_verbs/ninja_empulse.dm
- code/modules/ninja/suit/n_suit_verbs/ninja_stealth.dm
- code/modules/ninja/suit/suit.dm
Добавление всякого на шаттл, починка проводки и труб.
Фикс ниндзи.
> Изменение Acron-class и фикс Space Ninja

- _maps/configs/independent_acron.json
- code/acron/spaceninja.dm
- shiptest.dme
Reverts MysticalFaceLesS/Shiptest#109
> Revert "Изменение целей Space Ninja на Acron-class"

- _maps/configs/hard_prison_pod.json
- _maps/configs/independent_alone.json
- _maps/configs/independent_omega.json
- _maps/configs/inteq_colossus.json
- _maps/configs/inteq_hound.json
- _maps/configs/inteq_iron_maiden.json
- _maps/configs/inteq_talos.json
- _maps/configs/inteq_vaquero.json
- _maps/shuttles/independent/hard_prison_pod.dmm
- _maps/shuttles/independent/independent_alone.dmm
- _maps/shuttles/independent/independent_omega.dmm
- _maps/shuttles/inteq/inteq_colossus.dmm
- _maps/shuttles/inteq/inteq_hound.dmm
- _maps/shuttles/inteq/inteq_iron_maiden.dmm
- _maps/shuttles/inteq/inteq_talos.dmm
- _maps/shuttles/inteq/inteq_vaquero.dmm
> Добавление несколько солошипов, а так же не большие правки интеков.

- code/game/machinery/shuttle/shuttle_engine_types.dm
- code/modules/cargo/packs/machinery.dm
Уменьшение разгона ионных двигателей и увеличение затрат топлива
Добавление набора для создания плазменного двигателя в карго
> Нерф ионных двигателей и добавление набора в карго

- _maps/configs/independent_hardprisonpod.json
- _maps/shuttles/independent/independent_alone.dmm
- _maps/shuttles/independent/independent_hardprisonpod.dmm
Небольшие исправление шипов Alone и Hard Prison Pod(HPP).
> Небольшие исправление двух шипов

- _maps/configs/independent_acron.json
> Апдейт Акрона

- code/__DEFINES/tgs.dm
- code/modules/tgs/core/datum.dm
This pull request updates the TGS DMAPI to the latest version. Please note any breaking or unimplemented changes before merging.
:cl:
/:cl:
> Automatic TGS DMAPI Update (#2454)

- _maps/configs/solgov_inkwell.json
- _maps/shuttles/solgov/solgov_inkwell.dmm
Correct, there is a ship freeze currently, but I have received permission from @Apogee-dev to create the PR for this vessel, as it was a ship I've been working on since at least early-to-mid August.
If any other maptainer would like to overrule Apogee, I'd be more than happy to temporarily close the PR. Until then, here it is! Hello everyone! Mr. SolGov here again to add yet another ship to be tested!
This PR adds a completely new vessel, that being the **Inkwell-class Supply Freighter**, a ship known for its vast cargo space!
57](https://github.com/shiptest-ss13/Shiptest/assets/77556824/9a70d97e-ab17-45af-a690-e528574b95cb)
59](https://github.com/shiptest-ss13/Shiptest/assets/77556824/2d9d6d0a-85e2-4c46-9754-d49f15be0560)
With extra starter money, three sonnensöldners, and three miners, …
> Adds the Inkwell-class Supply Freighter (#2385)

- code/datums/components/forensics.dm
- code/datums/elements/decals/blood.dm
Ports the rest of
[https://github.com/BeeStation/BeeStation-Hornet/pull/3111](url), which seems to fix it.
Blub :)
:cl:
fix: bloodstains no longer steal the shape of the first item to spill blood
/:cl:
:cl:
/:cl:
> Fixes bloodstains getting stuck (#2456)

- _maps/configs/independent_acron.json
- _maps/shuttles/independent/independent_escapepod.dmm
Исправление мелких  багов
:cl:
/:cl:
> Обновление экспейд пода.

- code/modules/surgery/organs/tongue.dm
Русификация акцента языка lizard(Сарати)
Русификация акцента языка fly(не молей)
Русификация акцента языка uwu(кошачьего)
Русификация фраз зомби(tongue/zombie)
Русификация акцентов
Добавлены замены на русском языке для lizard языка
Добавлены замены на русском языке для fly языка
Добавлены замены на русском языке для uwuspeak языка
Заменена фраза у языка zombie с английской на русскую 
Теперь акценты работают и на русской раскладке 
:cl:
/:cl:
> Русификация акцентов

- code/datums/components/edit_complainer.dm
- code/modules/mob/living/living_say.dm
you will now be warned prior to succumbing to death by talking
"AAAARGHR AARHGRGH AARGH"
Blorbo seizes up and falls limp, their eyes dead and lifeless. "AAAARGHR AARHGRGH AARGH"
Blorbo seizes up and falls limp, their eyes dead and lifeless. 
:cl:
tweak: you will now be warned before succumbing when talking in hardcrit /:cl:
:cl:
server: …
> Add a warning for last words. (#2476)

- code/modules/clothing/factions/gezena.dm
- code/modules/power/cell.dm
- code/modules/projectiles/guns/faction/gezena/energy_gunsword.dm
Finishes up PH strings for PGF items.
:cl:
fix: PGF items now have real names and descriptions. /:cl:
:cl:
/:cl:
> Finishes up PH strings for PGF items (#2475)

- _maps/shuttles/syndicate/syndicate_cybersun_kansatsu.dmm
- _maps/shuttles/syndicate/syndicate_gorlex_hyena.dmm
- _maps/shuttles/syndicate/syndicate_gorlex_komodo.dmm
- _maps/shuttles/syndicate/syndicate_twinkleshine.dmm
- code/game/machinery/porta_turret/portable_turret.dm
Adds bespoke factioned turrets for the syndicate and adds them to relevant syndicate ships
IFF(2025)
:cl:
add: Syndicate groups have reported new models of turrets being attached to their ships.
/:cl:
:cl:
/:cl:
> syndicate turret update (#2478)

- code/__DEFINES/say.dm
- code/game/objects/effects/anomalies/anomalies_static.dm
Grammar Fix + another feature for an anomaly (no spoilers 
content
:cl:
add: Static Anomalies are now even WORSE. Not balance wise. Roleplay wise.
/:cl:
:cl:
/:cl:
> Static Whispers (#2465)

- code/modules/overmap/ships/controlled_ship_datum.dm
> "Fixes" Subshuttle Error (#2477)

- code/modules/overmap/ships/controlled_ship_datum.dm
> Strangles the CI with my bare hands (#2482)

- code/modules/overmap/ships/controlled_ship_datum.dm
I really want this to work this time.
:cl:
/:cl:
> God (#2486)

- code/modules/overmap/missions/research_mission.dm
the scanner machine updates its icon now
player feedback
:cl:
fix: The polymodial sensor array now properly changes icon_state. /:cl:
:cl:
/:cl:
> Fixes scanner icon setting (#2479)

- code/game/objects/effects/anomalies/anomalies_plasmasoul.dm
removes passive plasmasoul gas making
less lag
:cl:
balance: passive plasmasoul gas making is gone
fix: plasmasouls no longer make infinite free lag
/:cl:
:cl:
/:cl:
> Changes Plasmasoul (#2471)

- _maps/shuttles/independent/independent_bubble.dmm
Adjust mobile docking port to ensure east facing, added stationary docking port.
The Bubble lacked a docking port for shuttles, and would rotate in flight.
Expanded map height (Y) by one to fit stationary dock. Added stationary dock to south airlock for shuttle use:
055811](https://github.com/shiptest-ss13/Shiptest/assets/14267245/0d8da4b2-a9f3-4de1-baf5-155ad3829a70)
Moved mobile dock to north pad and corrected `preferred_direction` (was north!) and `port_direction`. This ensured east-facing during transit.
With the expanded map height (Y), Bubble map was now a square and would land facing north. Expanded map length (X) to make it rectangular again, and now it correctly lands facing east.
Shuttle docking adds options. Consistent ship facing prevents issues.
:cl:
tweak: Bubble now …
> Bubble docking adjustment (#2415)

- _maps/RandomRuins/JungleRuins/jungle_spider.dmm
- _maps/RandomRuins/RockRuins/rockplanet_clock.dmm
- _maps/RandomRuins/RockRuins/rockplanet_harmfactory.dmm
- _maps/RandomRuins/SandRuins/whitesands_surface_golemhijack.dmm
- _maps/RandomRuins/SandRuins/whitesands_surface_youreinsane.dmm
- _maps/RandomRuins/SpaceRuins/dangerous_research.dmm
- _maps/RandomRuins/SpaceRuins/mechtransport.dmm
- _maps/RandomRuins/SpaceRuins/nuclear_dump.dmm
- _maps/RandomRuins/SpaceRuins/provinggrounds.dmm
- _maps/RandomRuins/SpaceRuins/singularity_lab.dmm
- _maps/map_catalogue.txt
- code/datums/ruins/jungle.dm
- code/datums/ruins/rockplanet.dm
- code/datums/ruins/space.dm
- code/datums/ruins/whitesands.dm
- code/game/area/areas/ruins/space.dm
- code/game/objects/effects/spawners/lootdrop.dm
Reverts MysticalFaceLesS/Shiptest#160
> Revert "Massive Ruin Fixes + Removals PR (#2334)"

- code/modules/mining/equipment/kinetic_crusher.dm
- mod_celadon/fixes/_fixes.dm
- mod_celadon/fixes/_fixes.dme
- mod_celadon/fixes/code/syndiecrusher.dm
- mod_celadon/mod_celadon.dme
Фикс синди-крашера + создание папки fixes
> Фикс синди-крашера

- mod_celadon/balance/_balance.dm
- mod_celadon/balance/_balance.dme
- mod_celadon/balance/code/collector.dm
Ребаланс радиационных коллекторов, который увеличивает их выработку до 400 кВт за штуку
close #0
```yml
🆑
balance: Ребаланс радиационных коллекторов
🆑
```
> Ребаланс радиационных коллекторов

- mod_celadon/qol/_qol.dme
- mod_celadon/qol/code/glasses.dm
Добавляет возможность создавать meson sunglasses в меню крафта
close #0
```yml
🆑
rscadd: Добавил в игру что-то новое
🆑
```
> Добавление крафта Meson Sunglasses

- _maps/_mod_celadon/configs/inteq_hammerhead.json
- _maps/_mod_celadon/shuttles/inteq/inteq_hammerhead.dmm
> Ремаппинг Хаммерхэда

- mod_celadon/elysium_stuff/code/hats.dm
> Фикс тюрбанов сепаратистов

- _maps/_mod_celadon/shuttles/nanotrasen/nanotrasen_gecko.dmm
> Мини-фикс Гекко

- _maps/_mod_celadon/configs/syndicate_gorlex_komodo.json
- _maps/_mod_celadon/shuttles/syndicate/syndicate_gorlex_komodo.dmm
Немного забаланшены шмотки, наконец-то сделан нормальный инженер и шахтёр, так же сделан отдельно бармен, ассистухи были убиты
> Ремаппинг + починка Комода

- mod_celadon/fixes/_fixes.dme
- mod_celadon/fixes/code/field_gen.dm
ПР добавляет резисты генераторам полей (duh), чтобы эммитеры более не уничтожали их
> Добавление резистов генераторам полей

- mod_celadon/drakeborgs/code/newforrobots.dm
- mod_celadon/drakeborgs/code/rnd.dm
> Фикс дрейкборгов

- code/modules/mining/equipment/explorer_gear.dm
Убирает мёрджконфликт, вызванный оффами
> Убран мёрджконфликт

- _maps/_mod_celadon/RandomRuins/IceRuins/icemoon_surface_corporate_rejects.dmm
- _maps/_mod_celadon/RandomRuins/SpaceRuins/crashedship.dmm
- _maps/_mod_celadon/RandomRuins/WasteRuins/wasteplanet_clowncrash.dmm
- _maps/_mod_celadon/RandomRuins/WasteRuins/wasteplanet_fortress_of_solitide.dmm
- mod_celadon/maps/code/random_ruins.dm
Уэээээ, фикс руин. Нужно дополнительно выносить датумы руин в модуль, но сейчас я не могу этим заниматься
> Фиксы руин

- mod_celadon/solfed_stuff/code/solfed_other_stuff.dm
ПР добавляет шмотку, которую я забыл добавить для СолФедовских элизиумцев
> Добавление забытой шмотки

- mod_celadon/drakeborgs/code/newforrobots.dm
ПР чинит модели дрейкборгов, теперь они не двухтайловые
> Фикс моделей дрейкборгов

- mod_celadon/qol/_qol.dme
- mod_celadon/qol/code/fax.dm
Факсы более не блочат весь тайл, позволяя использовать вещи, что находятся рядом. Пример: https://discord.com/channels/1100198143456465067/1262179448518737951
> Фикс факсов

- _maps/_mod_celadon/outpost/elysium_ice.dmm
- mod_celadon/balance/_balance.dme
- mod_celadon/balance/code/ionrifle.dm
- mod_celadon/items/code/under.dm
- mod_celadon/loadout/code/headwear.dm
- mod_celadon/loadout/code/uniform.dm
ПР делает следующие вещи:
1. Теперь снаряд ионки наносит 10 бёрн урона при попадании
2. Теперь обычные/улучшенные/большие оружейные батареи могут быть вставлены в ионную винтовку и карабин
3. Теперь ионная винтовка имеет размер bulky, а не large
4. В лодаут добавлена пиратская шляпа (headwear) и тактикульная жилетка (uniform)
5. На ледяном аванпосту убраны торчащие наружу трубы
> Minor changes

- code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
- mod_celadon/balance/README.md
- mod_celadon/balance/code/elite.dm
- mod_celadon/mobs/code/simple_animal/wizard_constructs.dm
ПР перебалансирует Пандору и её мобов, а так же меняет сундуки с элиток
> Небольшая перебалансировка Пандоры и элиток

- code/__DEFINES/inventory.dm
- code/modules/clothing/head/_head.dm
- code/modules/clothing/masks/_masks.dm
- code/modules/clothing/spacesuits/hardsuit.dm
- code/modules/clothing/suits/_suits.dm
- code/modules/mob/living/carbon/human/update_icons.dm
- mod_celadon/balance/README.md
- mod_celadon/balance/_balance.dme
- mod_celadon/balance/code/gloves.dm
- mod_celadon/balance/code/hardsuit.dm
- mod_celadon/items/code/coats.dm
- mod_celadon/items/code/external_wears.dm
- mod_celadon/items/code/suits.dm
- mod_celadon/items/code/under.dm
ПР содержит следующие изменения:
- Очередная перебалансировка замедлений хардсьютов: теперь ОБР хардсьюты имеют замедление, хадрсьюты Синдиката же имеют увеличенное замедление в режиме ЕВА и уменьшенное в боевом режиме
- Перебалансировка перчаток. Теперь боевые перчатки имеют броню, при этом прототипные эксплорерские перчатки имеют броню и резист к электричеству чуть больше
- Переопределение путей для таяр, теперь у них более красивые шлемы и маски
- Оптимизация кода
> Сборник изменений

- _maps/_mod_celadon/RandomRuins/WasteRuins/wasteplanet_ruined_abductor_ship.dmm
- mod_celadon/maps/code/ruins/ruin.dm
ПР добавляет новую руину. Потерпевший крушение корабль абдукторов, чьи биологические эксперименты вырвались на свободу
> Новая руина для мусорной планеты

- mod_celadon/fixes/code/railings.dm
ПР возвращает старые спрайты забора, так как новые являются ужасом
> Возвращение старых спрайтов заборов (railing)

- code/modules/mob/living/carbon/human/species.dm
> Исправление поломки компила

- code/game/objects/items/devices/taperecorder.dm
- code/modules/surgery/organs/stomach.dm
- mod_celadon/fixes/README.md
- mod_celadon/items/code/items.dm
- mod_celadon/lanius/README.md
- mod_celadon/lanius/code/bodyparts.dm
- mod_celadon/lanius/code/lanius.dm
ПР вносит в код следующие изменения:
- Ланиусы более не блюют от того, что им мерзко (от поедания обычной еды), теперь они теряют возможность нормально двигаться, а так же теряют насыщение каждый тик
- Ланиусы более не могут носить парики
- Диктофон получил изменения (более не переводит любой язык на общегаллактический, так же изменены его описание и название)
> Фиксы ланиусов

- _maps/_mod_celadon/shuttles/solfed/solfed_anomaly.dmm
> Редактирование Anomaly

- _maps/_mod_celadon/shuttles/solfed/solfed_anomaly.dmm
Изменения Anomaly:
- добавлены: пара вендоматов, раздатчик безалкогольных напитков
- изменена дальность облучения "Heartbeat" (теперь не должна так далеко бить)
- немного изменён мостик
- перенесён радкостюм и душ в карго
> Небольшие изменения Anomaly

- mod_celadon/structures/_structures.dme
> Фикс путей, ломающих компил билда

- _maps/_mod_celadon/outpost/elysium_asteroid.dmm
- _maps/_mod_celadon/outpost/elysium_ice.dmm
ПР убирает ёлки с обоих аванпостов + микрофикс после оффов
> Снос ёлок. Никакого праздника

- mod_celadon/items/code/items.dm
ПР меняет направление маппинг хэлперов для флагов, теперь флаги будут ставиться на том же тайле, куда их ставят, а не через тайл (сука, ненавижу минусы в скобках)
>  Инверсия направлений маппинг хэлперов для флагов

- mod_celadon/celadon_modsuits/code/modsuit.dm
ПР делает то, что написано в тайтле
> Фикс плейсхолдеров + минибафф кэпМОД-а
